name: test

on:
  pull_request:
    branches: [main, master, staging, dev, feat/**, fix/**]
  push:
    branches: [main, master, staging, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ${{ github.event_name == 'push' && 'ci' || 'pr' }}
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

jobs:
  forge-test:
    name: Foundry project
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: bullfrogsec/bullfrog@1831f79cce8ad602eef14d2163873f27081ebfb3 # v0.8.4
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable

      - name: Run Forge fmt check
        run: forge fmt --check

      - name: Run Forge tests
        run: forge test --isolate

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        id: coverage
        env:
          COVERAGE: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
